### PR TITLE
Fix rspecs

### PR DESCRIPTION
**Pull request by ldodds**
Working branch to get the tests up and running again.

### CODE REVIEW

**Comment by jhigman** [comment]
@leigh This branch now has a travis config and a passing build - think it might be worth merging this down, and making any further changes in other branches (so at least we'll have a running CI)

**Comment by ldodds** [comment]
Yep, makes sense to me. Will be good to have this up and running in travis.

**Comment by ldodds** [comment]
Are you happy to merge if you're working on this gem now?

**Comment by jhigman** [comment]
@ldodds Yes, I'll merge it down and let philip know

**Pull request merged**
